### ISSUE TITLE
index delete job is not multi user compliant

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/search_lucene#49]
what happens:
1. index for the logged-in user is created
2. all deleted files are queries from the db without the user being involved
3. index is cleanup for the given user
4. BUT NOT for other users

@butonic let's chat about this as well

**Comment by butonic** [comment]
The job has to be user specific so we can delete the file from the right index. Looking at the code there is bug #70. The delete job fetches all deleted fileids (from all users) and tries to delete them from a single users index. Next time the job is run for a different user. No deleted files will be found and the index will not get cleaned up.

Will get fixed by https://github.com/owncloud/search_lucene/issues/10
